In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/loan-approval-classification-data/loan_data.csv

In [24]:
data=pd.read_csv('/kaggle/input/loan-approval-classification-data/loan_data.csv')

In [25]:
data

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [26]:
mint=data['credit_score'].min()
print(mint)

390

In [27]:
le = LabelEncoder()
label = le.fit_transform(data['person_gender'])
data.drop("person_gender", axis=1, inplace=True)
 
# Appending the array to our dataFrame 
# with column name 'person_gender'
data["person_gender"] = label

In [28]:
le1 = LabelEncoder()
label1 = le1.fit_transform(data['previous_loan_defaults_on_file'])
data.drop("previous_loan_defaults_on_file", axis=1, inplace=True)
 
# Appending the array to our dataFrame 
# with column name 'person_gender'
data["previous_loan_defaults_on_file"] = label1

In [29]:
le2 = LabelEncoder()
label2 = le2.fit_transform(data['person_home_ownership'])
data.drop("person_home_ownership", axis=1, inplace=True)

data["person_home_ownership"] = label2

In [30]:
le3 = LabelEncoder()
label3 = le3.fit_transform(data['person_education'])
data.drop("person_education", axis=1, inplace=True)

data["person_education"] = label3

In [31]:
le4 = LabelEncoder()
label4 = le4.fit_transform(data['loan_intent'])
data.drop("loan_intent", axis=1, inplace=True)

data["loan_intent"] = label4
data

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status,person_gender,previous_loan_defaults_on_file,person_home_ownership,person_education,loan_intent
0,22.0,71948.0,0,35000.0,16.02,0.49,3.0,561,1,0,0,3,4,4
1,21.0,12282.0,0,1000.0,11.14,0.08,2.0,504,0,0,1,2,3,1
2,25.0,12438.0,3,5500.0,12.87,0.44,3.0,635,1,0,0,0,3,3
3,23.0,79753.0,0,35000.0,15.23,0.44,2.0,675,1,0,0,3,1,3
4,24.0,66135.0,1,35000.0,14.27,0.53,4.0,586,1,1,0,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,47971.0,6,15000.0,15.66,0.31,3.0,645,1,1,0,3,0,3
44996,37.0,65800.0,17,9000.0,14.07,0.14,11.0,621,1,0,0,3,0,2
44997,33.0,56942.0,7,2771.0,10.02,0.05,10.0,668,1,1,0,3,0,0
44998,29.0,33164.0,4,12000.0,13.23,0.36,6.0,604,1,1,0,3,1,1
44999,24.0,51609.0,1,6665.0,17.05,0.13,3.0,628,1,1,0,3,3,0

In [32]:
x=data[['person_age','person_income','person_emp_exp','loan_amnt','loan_int_rate','loan_percent_income','cb_person_cred_hist_length','credit_score','person_gender','previous_loan_defaults_on_file','person_home_ownership','person_education','loan_intent']]

In [33]:
y=data['loan_status']

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [35]:
# Initialize the Logistic Regression model
model = LogisticRegression()

# Fit the model on the training data
model.fit(x_train, y_train)

LogisticRegression()

In [36]:
y_pred = model.predict(x_test)

print("\nPredictions:")
print(y_pred)

Predictions:
[0 0 0 ... 0 0 0]

In [37]:
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

Accuracy: 0.791

In [38]:
print("Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(cm)

Confusion Matrix:
[[6875  115]
 [1766  244]]